INSERT INTO `country` (`country_id`, `country_name`) VALUES ('8', 'Albania');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('20', 'Algeria');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('99', 'American Samoa');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('73', 'Andorra');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('83', 'Angola');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('57', 'Antarctica (the territory South of 60 deg S)');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('32', 'Aruba');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('78', 'Australia');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('39', 'Bahrain');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('49', 'Barbados');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('11', 'Belize');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('46', 'British Indian Ocean Territory (Chagos Archipelago)');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('51', 'Brunei Darussalam');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('31', 'Burkina Faso');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('61', 'Burundi');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('36', 'Cambodia');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('100', 'Canada');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('98', 'Christmas Island');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('96', 'Cocos (Keeling) Islands');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('80', 'Cook Islands');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('23', 'Cuba');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('4', 'Cyprus');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('29', 'Czech Republic');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('76', 'Dominica');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('81', 'Ecuador');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('86', 'Egypt');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('58', 'Eritrea');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('71', 'Falkland Islands (Malvinas)');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('48', 'Faroe Islands');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('91', 'Fiji');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('63', 'Finland');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('37', 'France');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('18', 'French Guiana');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('25', 'French Polynesia');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('92', 'Ghana');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('62', 'Greece');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('27', 'Guernsey');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('17', 'Guinea');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('12', 'Hong Kong');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('72', 'Indonesia');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('22', 'Ireland');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('47', 'Israel');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('45', 'Jordan');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('16', 'Korea');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('33', 'Lebanon');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('24', 'Lesotho');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('10', 'Libyan Arab Jamahiriya');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('19', 'Lithuania');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('42', 'Luxembourg');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('74', 'Macedonia');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('94', 'Malaysia');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('95', 'Maldives');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('13', 'Mali');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('5', 'Marshall Islands');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('79', 'Martinique');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('26', 'Monaco');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('87', 'Mongolia');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('3', 'Montenegro');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('7', 'Morocco');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('34', 'Myanmar');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('75', 'Namibia');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('69', 'Netherlands');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('93', 'Nicaragua');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('41', 'Pakistan');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('35', 'Palau');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('52', 'Panama');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('68', 'Paraguay');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('15', 'Pitcairn Islands');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('67', 'Qatar');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('30', 'Reunion');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('82', 'Russian Federation');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('50', 'Saint Kitts and Nevis');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('14', 'Saint Pierre and Miquelon');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('85', 'Samoa');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('9', 'San Marino');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('54', 'Saudi Arabia');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('21', 'Senegal');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('60', 'Seychelles');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('38', 'Sierra Leone');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('40', 'Slovenia');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('77', 'Solomon Islands');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('1', 'Somalia');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('56', 'South Georgia and the South Sandwich Islands');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('65', 'Spain');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('6', 'Sudan');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('28', 'Svalbard & Jan Mayen Islands');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('44', 'Sweden');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('66', 'Syrian Arab Republic');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('55', 'Timor-Leste');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('43', 'Togo');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('89', 'Tonga');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('97', 'Trinidad and Tobago');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('2', 'Turkmenistan');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('53', 'Turks and Caicos Islands');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('88', 'Ukraine');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('59', 'United Arab Emirates');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('70', 'United Kingdom');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('90', 'Uzbekistan');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('64', 'Yemen');
INSERT INTO `country` (`country_id`, `country_name`) VALUES ('84', 'Zambia');


